[project]
name = "ai-agent-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "dotenv>=0.9.9",
    "openai>=3.14.1",
    "requests>=2.34.2",
    "wikipedia>=1.4.0",
]

[project.scripts]
ai-agent-learning = "ai_agent_learning:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
